-keep class org.tensorflow.** { *; }
-keep class org.tensorflow.lite.** { *; }
-dontwarn org.tensorflow.lite.gpu.**
-dontwarn org.tensorflow.lite.gpu.GpuDelegateFactory$Options$Backend
-keep class com.google.mlkit.** { *; }
-dontwarn com.google.mlkit.**
